---
- name: Setup Primary Agents
  hosts: bmn-hosts
  become: true
  tasks:
    - name: Install Puppet Agent
      apt:
        name: puppet-agent
        state: present

    - name: Configure Puppet Agent
      template:
        src: /ansible/templates/puppet.conf.j2
        dest: /etc/puppetlabs/puppet/puppet.conf
      notify: Restart Puppet Agent

  handlers:
    - name: Restart Puppet Agent
      service:
        name: puppet
        state: restart
