- name: Setup rsyslog
  hosts: security-services
  become: true
  tasks:
    - name: Install rsyslog package
      apt:
        name: rsyslog
        state: present

    - name: Copy rsyslog configuration file
      template:
        src: rsyslog.conf.j2
        dest: /etc/rsyslog.conf
      notify: restart rsyslog

  handlers:
    - name: restart rsyslog
      service:
        name: rsyslog
        state: restarted
