# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  
  # --- 
  # BMN Host Config 1
  # --
  config.vm.define "bmn-host-1" do |host1|
    host1.vm.box          = "ubuntu/bionic64"
    host1.vm.hostname     = "bmn-host-1"
    host1.vm.boot_timeout = 600

    host1.vm.provision "ansible" do |ansible|
      ansible.playbook       = "ansible/setup-primary-agents.yml"  
      ansible.inventory_path = "ansible/inventory.yml"
    end
  end

  # --- 
  # BMN Host Config 2
  # --
  config.vm.define "bmn-host-2" do |host2|
    host2.vm.box          = "ubuntu/bionic64"
    host2.vm.hostname     = "bmn-host-2"
    host2.vm.boot_timeout = 600

    host2.vm.provision "ansible" do |ansible|
      ansible.playbook       = "ansible/setup-primary-agents.yml"  
      ansible.inventory_path = "ansible/inventory.yml"
    end
  end

end
